version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:80"
    volumes:
      - ./public:/var/www/html
      - ./src:/var/www/html/src
    depends_on:
      - db

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: 'evaluation_librairie'
      MYSQL_USER: 'app_user'
      MYSQL_PASSWORD: 'app_password'
      MYSQL_ROOT_PASSWORD: 'mysql'
    volumes:
      - db_data:/var/lib/mysql
      - ./src/assets/SQL/library.sql:/docker-entrypoint-initdb.d/library.sql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: 'mysql'
    depends_on:
      - db

volumes:
  db_data: